### ISSUE TITLE
Question: Source

### ISSUE THREAD

**Issue by lvxhnat** [treatmesubj/Bloomberg_Stream#1]
Thanks for this project! It works for me. I am just curious as to what the link we are download the m3u8 segments from? can u explain a little where the cloud link gets the data from. Happy to take this conversation private.

**Comment by treatmesubj** [comment]
hey @lvxhnat,
cool that you found this project.

If you hop over to https://www.bloomberg.com/live in a web browser and open your dev tools to look at the network requests, you'll see your browser reaches out to an `akamaized.net` domain to fetch the `m3u8` and `ts` files. Looks like Bloomberg pays Akamai for Content Delivery Network (CDN) servers to cache video files around the world, so that the data is geographically close to whoever is requesting it to reduce latency.

Now that I know more than I did a few years ago, it would be cool to look into how it determines the closest server to point you to for the stream and utilize that rather than the one I hard-coded into my code, which is not optimal for most people

**Comment by lvxhnat** [comment]
@treatmesubj  thanks for the reply :) ill have a look
